server {
    listen 8080;
    host 127.0.0.1;

    # 1. / must answer to GET request ONLY
    location / {
        allow_methods GET;
        root /tmp/www;
    }

    # 2. /directory/ mapped to YoupiBanane with default index youpi.bad_extension
    # 3. Any file with .bla will execute cgi_test via POST
    location /directory/ {
        allow_methods GET POST;
        root /tmp/www/YoupiBanane;
        index youpi.bad_extension;
        cgi_extension .bla;
        cgi_path /tmp/www/cgi_test;
    }

    # 4. /post_body must answer anything to POST request with a maxBody of 100
    location /post_body {
        allow_methods POST;
        client_max_body_size 100;
        root /tmp/www;
        upload_store /tmp/www;
    }
}