server {
    listen 8080;
    host 127.0.0.1;
    server_name youpi_server;
    # Allow large bodies for the CGI test (in bytes)
    client_max_body_size 101000000;

    # / must answer to GET request ONLY
    location / {
        allow_methods GET;
        root /home/londardi/webserv_testing;
        index index.html;
    }

    # /post_body must answer anything to POST request with a maxBody of 100
    location /post_body {
        allow_methods POST;
        client_max_body_size 100;
        root /home/londardi/webserv_testing;
        upload_store /home/londardi/webserv_testing;
    }

    # /directory/ maps to YoupiBanane, sets the index, and handles the CGI .bla execution
    # We include POST here because the tester will POST to /directory/youpi.bla
    location /directory {
        allow_methods GET POST;
        root /home/londardi/webserv_testing/YoupiBanane;
        index youpi.bad_extension;
        
        # Any file with .bla as extension must answer to POST request
        cgi_extension .bla;
        cgi_path /home/londardi/Desktop/Webserv-20260610T144940Z-3-001/Webserv/cgi_test;
    }
}