server {
    listen 8080;                    # <--- CRITIQUE : Le testeur de 42 tourne sur le port 8080
    host 127.0.0.1;
    server_name localhost;
    client_max_body_size 100000000; # Permet de supporter les gros transferts du testeur

    # 1. / doit répondre aux requêtes GET uniquement
    location / {
        allow_methods GET;
        root /tmp/www;
        index index.html;
    }location /directory {
    allow_methods GET POST;
    root /home/eperrier/Code/Webserv/YoupiBanane;
    index youpi.bad_extension;
    cgi_extension .bla;
    cgi_path /home/eperrier/Code/Webserv/cgi_test;
}

    # 2. /directory/ doit répondre à GET et POST (pour le CGI)
    # Le dossier racine est YoupiBanane, et l'index par défaut est youpi.bad_extension
    # Toute requête se terminant par .bla doit exécuter le CGI cgi_test via POST
    location /directory/ {
        allow_methods GET POST;
        root /home/eperrier/Code/Webserv/YoupiBanane;
        index youpi.bad_extension;
        cgi_extension .bla;
        cgi_path /home/eperrier/Code/Webserv/cgi_test; # <--- Doit être cgi_test et non cgi_tester
    }

    # 3. /post_body doit accepter n'importe quoi en POST avec un maxBody de 100 octets
    location /post_body {
        allow_methods POST;
        client_max_body_size 100;
        root /tmp/www;
        upload_store /tmp/www; # Optionnel : utile si le testeur tente d'y écrire un fichier
    }
}