# eval.conf

# Server 1: Main Server on 127.0.0.1:8080
server {
    listen 8080;
    host 127.0.0.1;
    error_page 404 /custom_404.html;

    location / {
        allow_methods GET POST;
        root /tmp/www;
    }

    location /upload/ {
        allow_methods GET POST DELETE;
        root /tmp/www/upload;
        upload_store /tmp/www/upload;
    }

    location /limit/ {
        allow_methods POST;
        root /tmp/www;
        client_max_body_size 50;
        upload_store /tmp/www;
    }

    location /auto/ {
        allow_methods GET;
        root /tmp/www/auto;
        autoindex on;
    }

    location /index_test/ {
        allow_methods GET;
        root /tmp/www/index_dir;
        index my_index.html;
    }

    location /redir {
        allow_methods GET;
        root /tmp/www;
        return 301 /;
    }
}

# Server 2: Testing multiple servers on different ports
server {
    listen 8081;
    host 127.0.0.1;

    location / {
        allow_methods GET;
        root /tmp/www/port2;
        index index.html;
    }
}

# Server 3: Testing multiple servers on different hostnames (IP aliases)
server {
    listen 8080;
    host 127.0.0.2;

    location / {
        allow_methods GET;
        root /tmp/www/host2;
        index index.html;
    }
}