server {
    listen 8080;
    host 127.0.0.1;
    server_name main_server;
    client_max_body_size 1000000;
    
    # Custom error page test
    error_page 404 /custom_404.html;

    # Basic route to different directory
    location / {
        allow_methods GET;
        root /tmp/www/ultimate/www;
        index index.html;
    }

    # Test file uploads & autoindex
    location /upload {
        allow_methods GET POST;
        root /tmp/www/ultimate/www/upload;
        upload_store /tmp/www/ultimate/www/upload;
        autoindex on;
    }

    # Test DELETE permission separated from POST
    location /delete {
        allow_methods DELETE;
        root /tmp/www/ultimate/www/upload;
    }

    # Test client_max_body_size limits overrides
    location /limit {
        allow_methods POST;
        client_max_body_size 50;
        root /tmp/www/ultimate/www;
    }

    # Test CGI execution
    location /cgi-bin {
        allow_methods GET POST;
        root /tmp/www/ultimate/www;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }

    # Test HTTP Redirection
    location /redirect {
        return 301 /;
    }
}

# Test Multiple Servers & Multiple Ports
server {
    listen 8081;
    host 127.0.0.1;
    server_name backup_server;

    location / {
        allow_methods GET;
        root /tmp/www/ultimate/www8081;
        index index.html;
    }
}